name: "Checkout Branch"
description: "Checkout and switch to a branch"

inputs:
  branch_name:
    description: "Branch name to checkout and switch to"
    required: false
    default: main

runs:
  using: "composite"
  steps:
    - name: "Checkout branch"
      shell: bash
      run: |
        git checkout -B "${{ inputs.branch_name }}"
